# Atividade - 25/09/23

Documentação Numpy: https://numpy.org/doc/stable/

Enviar este arquivo preenchido com o nome do aluno para o e-mail: profbrunorespostas1@gmail.com e assunto: AD2301

In [1]:
nome = 'José Chacon'
print(nome)

José Chacon


### Questão 1:
Pesquisar na documentação da biblioteca numpy por propriedades e funções disponíveis para manipulação de Array de 1 dimensão (1darray) que não foram vistas em sala de aula. Citar cada uma delas com a explicação em forma de comentário e um exemplo.

Arquivo da aula sobre numpy: https://github.com/brunogomesifrn/respostas_ifrn/blob/main/python/Aulas/2023/numpy.ipynb

#### Propriedades - 1darray

In [ ]:
import numpy as np  #Importando a biblioteca

In [14]:
#Retorna o número de dimensões do array (sempre 1 para arrays unidimensionais).
 
array_dim = np.array([1, 2, 3, 4, 5])
print(array_dim.ndim)  


1


In [15]:
#T (ou transpose()): Retorna a transposição do array, trocando linhas por colunas.

array = np.array([[1, 2, 3], [4, 5, 6]])
transposta = array.T
print(transposta)

[[1 4]
 [2 5]
 [3 6]]


#### Funções - 1darray

In [16]:
#sum(): Calcula a soma dos elementos no array.

array_soma = np.array([1, 2, 3, 4, 5])
soma = array_soma.sum()
print(soma)  

15


In [17]:
#mean(): Calcula a média dos elementos no array.

array_m = np.array([1, 2, 3, 4, 5])
media = array_m.mean()
print(media)


3.0


In [18]:
#min() e max(): Encontram o valor mínimo e máximo no array, respectivamente.

elements = np.array([1, 2, 3, 4, 5])
minimo = elements.min()
maximo = elements.max()
print(minimo, maximo)  

1 5


In [19]:
# argmax() e argmin(): Encontram os índices do valor máximo e mínimo no array, respectivamente.

indices = np.array([5, 2, 1, 4, 3])
indice_maximo = indices.argmax()
indice_minimo = indices.argmin()
print(indice_maximo, indice_minimo)

0 2


In [20]:
# sort(): Ordena os elementos no array em ordem crescente.

array = np.array([5, 2, 1, 4, 3])
array.sort()
print(array)

[1 2 3 4 5]


### Questão 2
Crie um exemplo de criação de um array de 2 dimensões (2darray).

In [21]:

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Questão 3
Cite funções disponíveis no numpy que criam array de duas dimenões (2darray) já preenchido de forma automática.

In [22]:

array_zeros = np.zeros((3, 3))  # Cria uma matriz 3x3 de zeros.

print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:

array_uns = np.ones((2, 4))  # Cria uma matriz 2x4 de uns.

print(array_uns)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
