# NumPy

Numpy = Numerical Python

Pacote para operações matemáticas que suportam estatísticas, análise de dados, inteligência artificial, entre outros.
- Numpy trabalha com o conceito de array e tem suporte a leitura de datasets;
- Disponibiliza diversas funções de cálculos matemáticos e estatísticos;

- Site ofocial: https://numpy.org
- Instalação: pip install numpy

## Array NumPy

Nomeclatura oficial: ndarray

- 1-D array - array com 1 dimensão: vetor, lista (Um Array é uma lista de dados do mesmo tipo.)
- 2-D array - array com 2 dimensões: matriz
- 3-D array - array com 3 ou mais dimensões: tensor

In [3]:
# Importando a biblioteca

import numpy as np

In [4]:
# Criando um array numpy - função array()

array01 = np.array([2,5,4,23,10,22])

print(array01)

[ 2  5  4 23 10 22]


In [5]:
# type() - É uma função para visualizar o tipo do dado
print(type(array01))

<class 'numpy.ndarray'>


# Propriedades

In [7]:
# dtype - Imprime o tipo dos dados do array numpy

print(array01.dtype)

int32


In [8]:
#shape - Dimensão e quantidade de elementos do array Numpy
print(array01.shape)

(6,)


In [9]:
# size - Quantidade de elementos do array

print(array01.size)

6


# Funções

In [13]:
#Cumsum() - Gera um novo array Numpy com soma acumulada dos elementos

array01 = np.array([2,5,4,23,10,22])

print(array01.cumsum())

[ 2  7 11 34 44 66]


In [16]:
# arange() - 
array01 = np.arange(10)
print(array01)

array01 = np.arange(2,10,2)
print(array01)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [19]:
'''
linspace()- Gera um array numpy que:
(1,10,4)

1 - Número inicila do intervalo
10 - Número final do intervalo
4 - Deve preencher um array com 4 elementos deste intervalo com o mesmo espaçamento de elementos entre eles
'''

array03 = np.linspace(1,10,4)
print(array03)

[ 1.  4.  7. 10.]


In [21]:
# equal() - compara os elementos

array04 = np.array([1,4,7,4])
array05 = np.array([8,7,7,4])

print(np.equal(array04, array05))

[False False  True  True]


In [22]:
# array_equal() compara se o array é igual ao outro

array04 = np.array([1,4,7,4])
array05 = np.array([8,7,7,4])

print(np.array_equal(array04, array05))

False


# Slicing de Arrays numpy (fatiamento)

In [23]:
array06 = np.arange(20)
print(array06)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
#Vá da posição 5 até a 15 saltando de 2 em 2
print(array06[5:15:2])

[ 5  7  9 11 13]
